services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: city_green_sqlserver
    restart: always
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: CityGreen123!
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql

volumes:
  sqldata: